In [135]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Solution1 : Perceptron Training Rule & Gradient Descent

In [136]:
# loading the dataset.

data = np.array([
    [2,3,0],
    [4,5,0],
    [11,11,1],
    [4,11,1],
    [12,5,0],
    [5,2,0],
    [6,1,0],
    [6,3,0],
    [2,10,1],
    [4,7,1],
    [13,8,0],
    [1,6,1],
    [6,9,1],
    [10,12,1],
    [8,3,0],
    [2,8,1]
])


In [137]:
input_data = pd.DataFrame(data, columns=['x1','x2','target'])
input_data

x1  x2  target
0    2   3       0
1    4   5       0
2   11  11       1
3    4  11       1
4   12   5       0
5    5   2       0
6    6   1       0
7    6   3       0
8    2  10       1
9    4   7       1
10  13   8       0
11   1   6       1
12   6   9       1
13  10  12       1
14   8   3       0
15   2   8       1

In [138]:
x = input_data.drop(['target'], axis=1).values
y = input_data['target'].values

In [139]:
def predict(row, weights):
    activation = weights[0]
    for i in range(len(row)-1):
        activation += weights[i+1] * row[i]
    return 1.0 if activation >= 0.0 else 0.0

In [140]:
def perceptron(x, y, itr):
    wts = [0.0 for i in range(len(x[0]))]
    errors=[]
    for i in range(itr):
        err = 0
        for x1, target in zip(x,y):
            delta_w = learning_rate*(target - predict(x1, wts))
            wts[1:] += delta_w * x1
            wts[0] += delta_w
            err += int(delta_w != 0.0)
        errors.append(err)
        print("errors=",errors, "-->> weights=", wts)

In [141]:
itr = 15
perceptron(x,y,itr)

errors= [10] -->> weights= [0.20000000000000004, -0.09999999999999998, 3.6000000000000005]
errors= [10, 10] -->> weights= [0.4, -0.19999999999999996, 7.200000000000001]
errors= [10, 10, 10] -->> weights= [0.6, -0.2999999999999998, 10.8]
errors= [10, 10, 10, 10] -->> weights= [0.7999999999999999, -0.3999999999999997, 14.399999999999999]
errors= [10, 10, 10, 10, 7] -->> weights= [0.8999999999999999, 0.10000000000000031, 17.299999999999997]
errors= [10, 10, 10, 10, 7, 11] -->> weights= [0.9999999999999999, -0.3999999999999997, 20.399999999999995]
errors= [10, 10, 10, 10, 7, 11, 7] -->> weights= [1.0999999999999999, -0.6999999999999997, 22.899999999999995]
errors= [10, 10, 10, 10, 7, 11, 7, 6] -->> weights= [1.3, 1.1102230246251565e-16, 26.099999999999994]
errors= [10, 10, 10, 10, 7, 11, 7, 6, 11] -->> weights= [1.4000000000000001, -0.4999999999999998, 29.199999999999992]
errors= [10, 10, 10, 10, 7, 11, 7, 6, 11, 7] -->> weights= [1.5000000000000002, 1.1102230246251565e-16, 32.099999999999

## Delta Rule 

In [132]:
# Make a prediction with weights
def predict(row, weights):
    activation = weights[0]
    for i in range(len(row)-1):
        activation += weights[i+1] * row[i]
    return 1.0 if activation >= 0.0 else 0.0

In [133]:
def train_weights(train, l_rate, n_epoch):
    weights = [0.0 for i in range(len(train[0]))]
    for epoch in range(n_epoch):
        print(epoch)
        sum_error = 0.0
        for row in train:
            prediction = predict(row, weights)
            error = row[-1] - prediction
            sum_error += error**2
            weights[0] = weights[0] + l_rate * error
            for i in range(len(row)-1):
                weights[i+1] = weights[i+1] + l_rate * error * row[i]
        print('>epoch=%d, lrate=%.3f, error=%.3f' % (epoch, l_rate, sum_error))
    return weights

In [134]:
learning_rate = 0.1
n_epoch = 10
weights = train_weights(data, learning_rate, n_epoch)
print(weights)

0
>epoch=0, lrate=0.100, error=3.000
1
>epoch=1, lrate=0.100, error=3.000
2
>epoch=2, lrate=0.100, error=3.000
3
>epoch=3, lrate=0.100, error=3.000
4
>epoch=4, lrate=0.100, error=3.000
5
>epoch=5, lrate=0.100, error=3.000
6
>epoch=6, lrate=0.100, error=3.000
7
>epoch=7, lrate=0.100, error=3.000
8
>epoch=8, lrate=0.100, error=5.000
9
>epoch=9, lrate=0.100, error=2.000
[-1.0999999999999999, -2.2000000000000006, 2.5]


# Solution 2

In [289]:
import keras #library for neural network
import pandas as pd #loading data in table form  
import seaborn as sns #visualisation 
import matplotlib.pyplot as plt #visualisation
import numpy as np # linear algebra
from sklearn.preprocessing import normalize #machine learning algorithm library

In [290]:
data = pd.read_csv('iris.csv')
data.head(10)

SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa
5          5.4         3.9          1.7         0.4  Iris-setosa
6          4.6         3.4          1.4         0.3  Iris-setosa
7          5.0         3.4          1.5         0.2  Iris-setosa
8          4.4         2.9          1.4         0.2  Iris-setosa
9          4.9         3.1          1.5         0.1  Iris-setosa

In [291]:
print(data["Name"].unique())

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


In [292]:
data.loc[data["Name"]=="Iris-setosa","Species"]=0
data.loc[data["Name"]=="Iris-versicolor","Species"]=1
data.loc[data["Name"]=="Iris-virginica","Species"]=2
print(data.head(10))

   SepalLength  SepalWidth  PetalLength  PetalWidth         Name  Species
0          5.1         3.5          1.4         0.2  Iris-setosa      0.0
1          4.9         3.0          1.4         0.2  Iris-setosa      0.0
2          4.7         3.2          1.3         0.2  Iris-setosa      0.0
3          4.6         3.1          1.5         0.2  Iris-setosa      0.0
4          5.0         3.6          1.4         0.2  Iris-setosa      0.0
5          5.4         3.9          1.7         0.4  Iris-setosa      0.0
6          4.6         3.4          1.4         0.3  Iris-setosa      0.0
7          5.0         3.4          1.5         0.2  Iris-setosa      0.0
8          4.4         2.9          1.4         0.2  Iris-setosa      0.0
9          4.9         3.1          1.5         0.1  Iris-setosa      0.0


In [293]:
x = data.drop(['Name'], axis=1).values
y = data['Species'].values
x_normalized=normalize(x,axis=0)
print("Examples of X_normalised\n",x_normalized[:3])

Examples of X_normalised
 [[0.07056264 0.09265065 0.02754646 0.01150299 0.        ]
 [0.06779548 0.07941484 0.02754646 0.01150299 0.        ]
 [0.06502832 0.08470916 0.02557886 0.01150299 0.        ]]


In [294]:
#Creating train,test and validation data

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.20)

In [295]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(3), max_iter=1000)
mlp.fit(X_train, y_train.ravel())

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=3, learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=1000,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [296]:
predictions = mlp.predict(X_test)

In [297]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

[[ 8  0  0]
 [ 0 10  0]
 [ 0 12  0]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00         8
         1.0       0.45      1.00      0.62        10
         2.0       0.00      0.00      0.00        12

    accuracy                           0.60        30
   macro avg       0.48      0.67      0.54        30
weighted avg       0.42      0.60      0.47        30



C:\Users\admin\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [303]:
# Using Keras Neural network module
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline

In [304]:
# define the keras model

def baseline_model():
    model = Sequential()
    model.add(Dense(1, activation='sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

In [307]:
estimator = KerasClassifier(build_fn=baseline_model, epochs=200, batch_size=5, verbose=0)
kfold = KFold(n_splits=10, shuffle=True)
results = cross_val_score(estimator, X_train, y_train, cv=kfold)
print("Cross Validation Report")
print(results)
print("Baseline Accuracy For 3 Neurons Single Layer: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

Cross Validation Report
[0.25       0.41666666 0.58333331 0.66666669 0.83333331 0.33333334
 0.75       0.66666669 0.66666669 0.66666669]
Baseline Accuracy For 3 Neurons Single Layer: 58.33% (17.87%)


## An NN with two hidden layers

In [308]:
data = pd.read_csv('iris.csv')
data.head(10)

SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa
5          5.4         3.9          1.7         0.4  Iris-setosa
6          4.6         3.4          1.4         0.3  Iris-setosa
7          5.0         3.4          1.5         0.2  Iris-setosa
8          4.4         2.9          1.4         0.2  Iris-setosa
9          4.9         3.1          1.5         0.1  Iris-setosa

In [309]:
x = data.drop(['Name'], axis=1).values
y = data['Name'].values

In [310]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
y = labelencoder.fit_transform(data['Name'])

In [311]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size = 0.1)

In [312]:
# define the keras model
def base_model():
    model = Sequential()
    model.add(Dense(9, input_dim=4, activation='relu'))
    model.add(Dense(3, activation='softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

In [313]:
estimator = KerasClassifier(build_fn=baseline_model, epochs=200, batch_size=5, verbose=0)
kfold = KFold(n_splits=10, shuffle=True)
results = cross_val_score(estimator, X_train, y_train, cv=kfold)
print("Cross Validation Report")
print(results)
print("Baseline Accuracy For The first hidden layer has 9 neurons. The second hidden layer has 3 neurons.: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))


Cross Validation Report
[0.35714287 0.2857143  0.21428572 0.78571427 0.78571427 0.15384616
 0.53846157 0.61538464 0.23076923 0.30769232]
Baseline Accuracy For The first hidden layer has 9 neurons. The second hidden layer has 3 neurons.: 42.75% (22.42%)
